<?php
/**
 * Reports Page — Generate & Export
 */
require_once __DIR__ . '/includes/auth.php';
requireLogin();

$pageTitle = 'Reports';
$db = getDB();

// Handle report generation (mocked for demo)
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'generate') {
    $type     = $_POST['type'] ?? 'engagement';
    $range    = $_POST['range'] ?? '30d';
    $platform = $_POST['platform'] ?? 'all';
    
    $title = ucfirst($type) . " Report - " . ucfirst($platform) . " (" . $range . ")";
    $stmt = $db->prepare("INSERT INTO reports (user_id, title, type, platform, date_range) VALUES (?, ?, ?, ?, ?)");
    $stmt->execute([$_SESSION['user_id'], $title, $type, $platform, $range]);
    
    header("Location: reports.php?msg=generated&id=" . $db->lastInsertId());
    exit;
}

$reports = $db->query("SELECT r.*, u.name as author FROM reports r JOIN users u ON r.user_id = u.id ORDER BY r.created_at DESC")->fetchAll();

include __DIR__ . '/includes/header.php';
?>

<section class="page active" id="page-reports">
    <div class="page-header">
        <div><h1>Reports</h1><p class="page-subtitle">Generate and export performance reports</p></div>
    </div>
    
    <?php if (isset($_GET['msg'])): ?>
    <div style="background:rgba(0,206,201,0.1);border:1px solid rgba(0,206,201,0.3);color:var(--success);padding:0.8rem 1rem;border-radius:var(--radius-sm);margin-bottom:1rem">
        <i class="fas fa-check-circle"></i> Report generated successfully!
    </div>
    <?php endif; ?>

    <div class="reports-layout">
        <div class="card">
            <div class="card-header"><h3>Generate Report</h3></div>
            <div class="card-body">
                <form method="POST">
                    <input type="hidden" name="action" value="generate">
                    <div class="form-row">
                        <div class="form-group"><label>Report Type</label>
                            <select class="select-styled" name="type">
                                <option value="engagement">Engagement Summary</option>
                                <option value="growth">Follower Growth</option>
                                <option value="content">Content Performance</option>
                                <option value="full">Full Analytics Report</option>
                            </select>
                        </div>
                        <div class="form-group"><label>Date Range</label>
                            <select class="select-styled" name="range">
                                <option value="7d">Last 7 Days</option>
                                <option value="30d" selected>Last 30 Days</option>
                                <option value="90d">Last 90 Days</option>
                            </select>
                        </div>
                        <div class="form-group"><label>Platform</label>
                            <select class="select-styled" name="platform">
                                <option value="all">All Platforms</option>
                                <option value="facebook">Facebook</option>
                                <option value="twitter">Twitter</option>
                                <option value="instagram">Instagram</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-row">
                        <button type="submit" class="btn btn-primary"><i class="fas fa-chart-bar"></i> Generate Report</button>
                        <button type="button" class="btn btn-secondary" id="exportCSV"><i class="fas fa-file-csv"></i> Export CSV</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="card">
            <div class="card-header"><h3>Report History</h3></div>
            <div class="card-body">
                <table class="data-table">
                    <thead><tr><th>Report Title</th><th>Generated By</th><th>Date</th><th>Actions</th></tr></thead>
                    <tbody>
                        <?php foreach ($reports as $r): ?>
                        <tr>
                            <td><strong><?= htmlspecialchars($r['title']) ?></strong><br><small style="color:var(--text-muted)"><?= ucfirst($r['type']) ?> • <?= ucfirst($r['platform']) ?> • <?= $r['date_range'] ?></small></td>
                            <td><?= htmlspecialchars($r['author']) ?></td>
                            <td><?= date('M j, Y', strtotime($r['created_at'])) ?></td>
                            <td>
                                <a href="api/reports.php?action=export_csv&type=<?= $r['type'] ?>&range=<?= $r['date_range'] ?>&platform=<?= $r['platform'] ?>" class="btn btn-ghost btn-sm" title="Download CSV"><i class="fas fa-file-csv"></i></a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                        <?php if (empty($reports)): ?>
                        <tr><td colspan="4" style="text-align:center;padding:2rem;color:var(--text-muted)">No reports generated yet.</td></tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<?php include __DIR__ . '/includes/footer.php'; ?>
